CREATE FUNCTION CC_DEVICE_GET_CURRENT_CONFIG (P_CC_DEVICE_ID INT)
  RETURNS D_VC_CLOB
  READS SQL DATA
  RETURN (SELECT TOP 1 CAST(CONFIG AS D_VC_CLOB) FROM CC_CONFIG_HISTORY WHERE CC_DEVICE_ID = P_CC_DEVICE_ID ORDER BY CONFIG_DATE DESC)



DROP FUNCTION CC_DEVICE_GET_CURRENT_CONFIG








