CREATE FUNCTION CC_DEVICE_GET_SCRIPT(IN P_ID INT) RETURNS D_SCRIPT
READS SQL DATA
BEGIN ATOMIC

  RETURN (

  SELECT SC.SCRIPT
    FROM CC_DEVICES C
    JOIN DEVICES D ON D.ID = C.DEVICE_ID
    JOIN DEVICE_TYPES T ON T.ID = D.DEVICE_TYPE_ID
    JOIN SCRIPTS SC ON SC.ID = T.GET_CONFIG_SCRIPT_ID
   WHERE C.ID = P_ID
   
   );     
     
END


DROP FUNCTION CC_DEVICE_GET_SCRIPT


--SELECT * FROM SCRIPTS
--SELECT * FROM CC_DEVICES
--SELECT * FROM DEVICE_TYPES




