CREATE PROCEDURE CC_DEVICE_REMOVE(IN P_ID INT) 
MODIFIES SQL DATA 
BEGIN ATOMIC 

DELETE FROM CC_LOG WHERE CC_DEVICE_ID = P_ID;
DELETE FROM CC_CONFIG_HISTORY WHERE CC_DEVICE_ID = P_ID;
DELETE FROM CC_DEVICES WHERE ID = P_ID;

END


DROP PROCEDURE CC_DEVICE_REMOVE

