CREATE PROCEDURE CC_DEVICE_SAVE_ERROR_LOG(IN P_DEVICE_ID INT,
                                          IN P_ERROR_LOG D_VC_CLOB) 
MODIFIES SQL DATA
BEGIN ATOMIC

  INSERT INTO CC_LOG(CC_DEVICE_ID, RESULT, ERROR_LOG)
  VALUES(P_DEVICE_ID, 'ERROR', P_ERROR_LOG);  

END 


DROP PROCEDURE CC_DEVICE_SAVE_ERROR_LOG 

