CREATE FUNCTION CC_DEVICE_HAS_UNCHECKED_CONFIG (P_CC_DEVICE_ID INT)
  RETURNS BOOLEAN
  READS SQL DATA
  RETURN (SELECT COUNT(*) 
            FROM CC_CONFIG_HISTORY
           WHERE CC_DEVICE_ID = P_CC_DEVICE_ID
             AND WHEN_CHECKED IS NULL) > 0



DROP FUNCTION CC_DEVICE_HAS_UNCHECKED_CONFIG







