CREATE FUNCTION CC_DEVICE_LAST_GET_CONFIG_DATE (P_CC_DEVICE_ID INT)
  RETURNS TIMESTAMP
  READS SQL DATA
  RETURN (SELECT MAX(LOG_DATE)
            FROM CC_LOG
           WHERE CC_DEVICE_ID = P_CC_DEVICE_ID)
             



DROP FUNCTION CC_DEVICE_LAST_GET_CONFIG_DATE







