CREATE TABLE DM_SCRIPTS (
  SCRIPT_ID INTEGER NOT NULL,
  OBJECT_ID INTEGER NOT NULL,
  CONSTRAINT DM_SCRIPTS_PK PRIMARY KEY (SCRIPT_ID,OBJECT_ID),
  CONSTRAINT DM_SCRIPTS_REF_OBJECTS FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS(ID) ON DELETE CASCADE,
  CONSTRAINT DM_SCRIPTS_REF_SCRIPTS FOREIGN KEY (SCRIPT_ID) REFERENCES SCRIPTS(ID) ON DELETE CASCADE
)


DROP TABLE DM_SCRIPTS




