CREATE TABLE H_CC_DEVICES (
  WHO_MODIFY INTEGER NOT NULL,
  WHEN_MODIFY TIMESTAMP DEFAULT SYSDATE NOT NULL,   
  ACTION D_TABLE_ACTION NOT NULL,
  ID INTEGER NOT NULL, 
  OLD_HOST D_VC,
  OLD_LOGIN D_VC,
  OLD_PWD D_VC,
  OLD_ENABLE_PWD D_VC,
  OLD_NAME D_VC,
  OLD_COMMENT D_VC_LONG,
  OLD_DEVICE_TYPE_NAME D_VC,
  OLD_CONNECT_TYPE D_CONNECT_TYPE,
  OLD_GET_CONFIG_INTERVAL D_VC,
  OLD_STORE_CONFIG_DAYS INTEGER,
  OLD_CC_OBJECT_NAME D_VC,
  NEW_HOST D_VC,
  NEW_LOGIN D_VC,
  NEW_PWD D_VC,
  NEW_ENABLE_PWD D_VC,
  NEW_NAME D_VC,
  NEW_COMMENT D_VC_LONG,
  NEW_DEVICE_TYPE_NAME D_VC,
  NEW_CONNECT_TYPE D_CONNECT_TYPE,
  NEW_GET_CONFIG_INTERVAL D_VC,
  NEW_STORE_CONFIG_DAYS INTEGER,
  NEW_CC_OBJECT_NAME D_VC,  
  CONSTRAINT H_CC_DEVICES_REF_USERS FOREIGN KEY (WHO_MODIFY) REFERENCES USERS(ID)
)


DROP TABLE H_CC_DEVICES





