CREATE FUNCTION PM_COUNT_VLAN_HOSTS(IN P_OBJECT_ID INT, IN P_VLAN INT) RETURNS INTEGER
READS SQL DATA
RETURN (
SELECT COUNT(DISTINCT CL.IP)
FROM PM_PORT_CLIENTS CL
JOIN PM_PORTS P ON P.ID = CL.PM_PORT_ID
JOIN PM_DEVICES D ON D.ID = P.PM_DEVICE_ID
WHERE CL.VLAN = P_VLAN
  AND CL.IP IS NOT NULL
  AND D.OBJECT_ID = P_OBJECT_ID
)


DROP FUNCTION PM_COUNT_VLAN_HOSTS







