CREATE PROCEDURE PM_DEVICE_REMOVE(IN P_ID INT) 
MODIFIES SQL DATA 
BEGIN ATOMIC 

FOR 
		SELECT ID
		FROM PM_PORTS
		WHERE PM_DEVICE_ID = P_ID
DO
  CALL PM_PORT_REMOVE(ID);
END FOR;

DELETE FROM PM_LOG WHERE PM_DEVICE_ID = P_ID;
DELETE FROM PM_ARP WHERE PM_DEVICE_ID = P_ID;
DELETE FROM PM_DEVICES WHERE ID = P_ID;

END


DROP PROCEDURE PM_DEVICE_REMOVE




