CREATE PROCEDURE PM_DEVICE_SAVE_REFRESH_LOG(IN P_DEVICE_ID INT,
                                            IN P_ERROR BOOLEAN,
                                            IN P_ERROR_LOG D_VC_LONG) 
MODIFIES SQL DATA
BEGIN ATOMIC

  INSERT INTO PM_LOG(PM_DEVICE_ID, RESULT, ERROR_LOG)
  VALUES(P_DEVICE_ID, CASEWHEN(P_ERROR,'ERROR','OK'), P_ERROR_LOG);  

END 


DROP PROCEDURE PM_DEVICE_SAVE_REFRESH_LOG

