CREATE PROCEDURE PM_OBJECT_REMOVE(IN P_ID INT) 
MODIFIES SQL DATA 
BEGIN ATOMIC 

DELETE FROM PM_VLANS WHERE PM_OBJECT_ID = P_ID;
DELETE FROM PM_ARP WHERE PM_OBJECT_ID = P_ID;
DELETE FROM PM_OBJECTS WHERE ID = P_ID;

END


DROP PROCEDURE PM_OBJECT_REMOVE

