CREATE FUNCTION PM_PORT_GET_CLIENTS(IN P_ID INTEGER, IN P_WHAT VARCHAR(4), IN P_VOICE BOOLEAN) RETURNS D_VC_CLOB
READS SQL DATA
BEGIN ATOMIC

	DECLARE L_RES D_VC_CLOB;
	FOR 
			SELECT IP, MAC, NAME FROM PM_PORT_CLIENTS WHERE PM_PORT_ID = P_ID AND VOICE=P_VOICE
	DO		
	  SET L_RES = L_RES || CASEWHEN(L_RES IS NULL, NULL, ';') || DECODE(P_WHAT, 'ip', IP, 'mac', MAC, 'name', NAME);
	END FOR;
	RETURN L_RES;

END


DROP FUNCTION PM_PORT_GET_CLIENTS
