CREATE PROCEDURE PM_PORT_ADD(
  OUT P_ID INT,
	IN P_PORT D_VC,
  IN P_COMMENT D_VC_LONG,
  IN P_TELCO D_VC,
  IN P_PATCH D_VC,
  IN P_LOCATION D_VC_LONG,
  IN P_PM_DEVICE_ID INT)
  
MODIFIES SQL DATA 
BEGIN ATOMIC 

INSERT INTO PM_PORTS(ID, PORT, COMMENT, TELCO, PATCH, LOCATION, PM_DEVICE_ID)
VALUES(DEFAULT, P_PORT, P_COMMENT, P_TELCO, P_PATCH, P_LOCATION, P_PM_DEVICE_ID);

SET P_ID = IDENTITY();

END




DROP PROCEDURE PM_PORT_ADD



