CREATE PROCEDURE PM_PORT_CLIENT_TO_ARCHIVE(IN P_ID INT) 
MODIFIES SQL DATA 
BEGIN ATOMIC 

DELETE FROM PM_ARP
WHERE (OBJECT_ID, IP, MAC) IN 
		(SELECT OBJECT_ID, IP, MAC
		   FROM V_PM_PORT_CLIENTS
		  WHERE ID = P_ID);
 
DELETE FROM PM_PORT_CLIENTS WHERE ID=P_ID;
 
END


DROP PROCEDURE PM_PORT_CLIENT_TO_ARCHIVE




