CREATE FUNCTION PM_PORT_GET_CLIENTS_QTY(IN P_ID INTEGER, IN P_VOICE BOOLEAN) RETURNS INTEGER
READS SQL DATA
RETURN (SELECT COUNT(0) FROM PM_PORT_CLIENTS WHERE PM_PORT_ID = P_ID AND VOICE=P_VOICE)


DROP FUNCTION PM_PORT_GET_CLIENTS_QTY





