CREATE PROCEDURE PORT_LOG_CHANGE(P_PORT_ID INT,
                         	       P_ACTION D_VC,
                                 P_VAL D_VC) 
MODIFIES SQL DATA 
BEGIN ATOMIC 
  INSERT INTO H_PM_PORTS_CHANGES(WHO_CHANGE, DEV_HOST, DEV_NAME, PORT, ACTION, VAL)
  SELECT USER_ID(), D.HOST, D.NAME, P.PORT, P_ACTION, P_VAL
    FROM PM_PORTS P
    JOIN PM_DEVICES PD ON PD.ID = P.PM_DEVICE_ID
    JOIN DEVICES D ON D.ID = PD.DEVICE_ID
   WHERE P.ID = P_PORT_ID;     
END




DROP PROCEDURE PORT_LOG_CHANGE

