CREATE TABLE USER_ROLES (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL,
  CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT USER_ROLES_REF_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT USER_ROLES_REF_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
)
 
 
 DROP TABLE USER_ROLES

