CREATE PROCEDURE USER_REMOVE(IN P_ID INT) 
MODIFIES SQL DATA 
BEGIN ATOMIC 

DELETE FROM USER_ROLES WHERE LOGIN = (SELECT LOGIN FROM USERS WHERE ID = P_ID);
DELETE FROM USERS WHERE ID = P_ID;

END


DROP PROCEDURE USER_REMOVE


