CREATE FUNCTION USER_IS_ADMIN (P_USER_ID INT)
  RETURNS BOOLEAN
  READS SQL DATA
  RETURN (SELECT COUNT(*) 
            FROM USERS U, USER_ROLES R 
           WHERE U.ID = P_USER_ID
             AND U.LOGIN = R.LOGIN
             AND R.ROLE = 'admin') > 0



DROP FUNCTION USER_IS_ADMIN





