CREATE TRIGGER TRG_PM_PORTS_BEFORE_INSERT 
BEFORE INSERT ON PM_PORTS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN ATOMIC

DECLARE L_OBJ_ID,L_CNT INT;

IF NEW.PM_PATCH_ID IS NOT NULL AND USER_ID() IS NOT NULL THEN

SELECT OBJECT_ID
  INTO L_OBJ_ID
  FROM PM_DEVICES
 WHERE ID = NEW.PM_DEVICE_ID;

SELECT COUNT(0)
  INTO L_CNT 
  FROM PM_DEVICES D
  JOIN PM_PORTS P ON P.PM_DEVICE_ID = D.ID
 WHERE D.OBJECT_ID = L_OBJ_ID
   AND P.PM_PATCH_ID = NEW.PM_PATCH_ID;
   
IF L_CNT > 0 THEN
  SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT='PM_PORTS_UNIQUE_PATCH_IN_OBJECT';
END IF;


END IF;

END





--DROP TRIGGER TRG_PM_PORTS_BEFORE_INSERT

