CREATE TRIGGER TRG_CC_OBJECTS_AFTER_UPDATE AFTER UPDATE ON CC_OBJECTS
REFERENCING NEW AS NEWROW OLD AS OLDROW
FOR EACH ROW
INSERT INTO H_CC_OBJECTS(WHO_MODIFY, ACTION, ID, NEW_NAME, NEW_COMMENT, NEW_MAP_NAME, 
                                                 OLD_NAME, OLD_COMMENT, OLD_MAP_NAME)
VALUES (USER_GET_AUTH(), 'U', NEWROW.ID, NEWROW.NAME, NEWROW.COMMENT, MAP_GET_NAME(NEWROW.MAP_ID), 
                                         OLDROW.NAME, OLDROW.COMMENT, MAP_GET_NAME(OLDROW.MAP_ID))



DROP TRIGGER TRG_CC_OBJECTS_AFTER_UPDATE

