CREATE TRIGGER TRG_MAPS_AFTER_INSERT AFTER INSERT ON MAPS
REFERENCING NEW ROW AS NEWROW
FOR EACH ROW
INSERT INTO H_MAPS(WHO_MODIFY, ACTION, ID, NEW_NAME, NEW_COMMENT)
VALUES (USER_ID(), 'I', NEWROW.ID, NEWROW.NAME, NEWROW.COMMENT)


DROP TRIGGER TRG_MAPS_AFTER_INSERT

