CREATE TRIGGER TRG_CC_OBJECTS_AFTER_DELETE AFTER DELETE ON CC_OBJECTS
REFERENCING OLD AS OLDROW
FOR EACH ROW
INSERT INTO H_CC_OBJECTS(WHO_MODIFY, ACTION, ID, OLD_NAME, OLD_COMMENT, OLD_MAP_NAME)
VALUES (USER_GET_AUTH(), 'D', OLDROW.ID, OLDROW.NAME, OLDROW.COMMENT, MAP_GET_NAME(OLDROW.MAP_ID))





DROP TRIGGER TRG_CC_OBJECTS_AFTER_DELETE


