CREATE TRIGGER TRG_OBJECTS_AFTER_DELETE 
AFTER DELETE ON OBJECTS
REFERENCING OLD AS OLD
FOR EACH ROW
INSERT INTO H_OBJECTS(WHO_MODIFY, ACTION, ID, OLD_MAP_NAME, OLD_NAME, OLD_COMMENT)
VALUES (USER_ID(), 'D', OLD.ID, (SELECT NAME FROM MAPS WHERE ID = OLD.MAP_ID), OLD.NAME, OLD.COMMENT)




DROP TRIGGER TRG_OBJECTS_AFTER_DELETE 



