CREATE TRIGGER TRG_CC_OBJECTS_AFTER_INSERT AFTER INSERT ON CC_OBJECTS
REFERENCING NEW AS NEWROW
FOR EACH ROW
INSERT INTO H_CC_OBJECTS(WHO_MODIFY, ACTION, ID, NEW_NAME, NEW_COMMENT, NEW_MAP_NAME)
VALUES (USER_GET_AUTH(), 'I', NEWROW.ID, NEWROW.NAME, NEWROW.COMMENT, MAP_GET_NAME(NEWROW.MAP_ID))


DROP TRIGGER TRG_CC_OBJECTS_AFTER_INSERT




