CREATE TRIGGER TRG_DM_FIELDS_AFTER_UPDATE AFTER UPDATE ON DM_FIELDS
REFERENCING NEW AS NEWROW OLD AS OLDROW
FOR EACH ROW
BEGIN ATOMIC

--DATE---------------------------------------------------------------------

IF OLDROW.DATE1 IS NOT NULL AND NEWROW.DATE1 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE1 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE2 IS NOT NULL AND NEWROW.DATE2 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE2 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE3 IS NOT NULL AND NEWROW.DATE3 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE3 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE4 IS NOT NULL AND NEWROW.DATE4 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE4 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE5 IS NOT NULL AND NEWROW.DATE5 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE5 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE6 IS NOT NULL AND NEWROW.DATE6 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE6 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE7 IS NOT NULL AND NEWROW.DATE7 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE7 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE8 IS NOT NULL AND NEWROW.DATE8 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE8 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE9 IS NOT NULL AND NEWROW.DATE9 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE9 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE10 IS NOT NULL AND NEWROW.DATE10 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE10 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE11 IS NOT NULL AND NEWROW.DATE11 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE11 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE12 IS NOT NULL AND NEWROW.DATE12 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE12 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE13 IS NOT NULL AND NEWROW.DATE13 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE13 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE14 IS NOT NULL AND NEWROW.DATE14 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE14 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE15 IS NOT NULL AND NEWROW.DATE15 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE15 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE16 IS NOT NULL AND NEWROW.DATE16 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE16 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE17 IS NOT NULL AND NEWROW.DATE17 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE17 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE18 IS NOT NULL AND NEWROW.DATE18 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE18 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE19 IS NOT NULL AND NEWROW.DATE19 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE19 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.DATE20 IS NOT NULL AND NEWROW.DATE20 IS NULL THEN
  UPDATE DM_DEVICES
     SET DATE20 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

--BOOL--------------------------------------------------------------------------

IF OLDROW.BOOL1 IS NOT NULL AND NEWROW.BOOL1 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL1 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL2 IS NOT NULL AND NEWROW.BOOL2 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL2 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL3 IS NOT NULL AND NEWROW.BOOL3 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL3 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL4 IS NOT NULL AND NEWROW.BOOL4 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL4 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL5 IS NOT NULL AND NEWROW.BOOL5 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL5 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL6 IS NOT NULL AND NEWROW.BOOL6 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL6 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL7 IS NOT NULL AND NEWROW.BOOL7 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL7 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL8 IS NOT NULL AND NEWROW.BOOL8 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL8 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL9 IS NOT NULL AND NEWROW.BOOL9 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL9 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL10 IS NOT NULL AND NEWROW.BOOL10 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL10 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL11 IS NOT NULL AND NEWROW.BOOL11 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL11 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL12 IS NOT NULL AND NEWROW.BOOL12 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL12 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL13 IS NOT NULL AND NEWROW.BOOL13 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL13 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL14 IS NOT NULL AND NEWROW.BOOL14 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL14 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL15 IS NOT NULL AND NEWROW.BOOL15 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL15 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL16 IS NOT NULL AND NEWROW.BOOL16 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL16 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL17 IS NOT NULL AND NEWROW.BOOL17 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL17 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL18 IS NOT NULL AND NEWROW.BOOL18 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL18 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL19 IS NOT NULL AND NEWROW.BOOL19 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL19 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.BOOL20 IS NOT NULL AND NEWROW.BOOL20 IS NULL THEN
  UPDATE DM_DEVICES
     SET BOOL20 = FALSE
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

--IP--------------------------------------------------------------------------

IF OLDROW.IP1 IS NOT NULL AND NEWROW.IP1 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP1 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP2 IS NOT NULL AND NEWROW.IP2 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP2 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP3 IS NOT NULL AND NEWROW.IP3 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP3 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP4 IS NOT NULL AND NEWROW.IP4 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP4 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP5 IS NOT NULL AND NEWROW.IP5 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP5 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP6 IS NOT NULL AND NEWROW.IP6 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP6 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP7 IS NOT NULL AND NEWROW.IP7 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP7 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP8 IS NOT NULL AND NEWROW.IP8 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP8 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP9 IS NOT NULL AND NEWROW.IP9 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP9 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP10 IS NOT NULL AND NEWROW.IP10 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP10 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP11 IS NOT NULL AND NEWROW.IP11 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP11 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP12 IS NOT NULL AND NEWROW.IP12 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP12 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP13 IS NOT NULL AND NEWROW.IP13 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP13 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP14 IS NOT NULL AND NEWROW.IP14 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP14 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP15 IS NOT NULL AND NEWROW.IP15 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP15 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP16 IS NOT NULL AND NEWROW.IP16 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP16 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP17 IS NOT NULL AND NEWROW.IP17 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP17 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP18 IS NOT NULL AND NEWROW.IP18 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP18 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP19 IS NOT NULL AND NEWROW.IP19 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP19 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.IP20 IS NOT NULL AND NEWROW.IP20 IS NULL THEN
  UPDATE DM_DEVICES
     SET IP20 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

--TEXT--------------------------------------------------------------------------

IF OLDROW.TEXT1 IS NOT NULL AND NEWROW.TEXT1 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT1 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT2 IS NOT NULL AND NEWROW.TEXT2 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT2 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT3 IS NOT NULL AND NEWROW.TEXT3 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT3 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT4 IS NOT NULL AND NEWROW.TEXT4 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT4 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT5 IS NOT NULL AND NEWROW.TEXT5 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT5 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT6 IS NOT NULL AND NEWROW.TEXT6 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT6 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT7 IS NOT NULL AND NEWROW.TEXT7 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT7 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT8 IS NOT NULL AND NEWROW.TEXT8 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT8 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT9 IS NOT NULL AND NEWROW.TEXT9 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT9 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT10 IS NOT NULL AND NEWROW.TEXT10 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT10 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT11 IS NOT NULL AND NEWROW.TEXT11 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT11 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT12 IS NOT NULL AND NEWROW.TEXT12 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT12 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT13 IS NOT NULL AND NEWROW.TEXT13 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT13 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT14 IS NOT NULL AND NEWROW.TEXT14 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT14 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT15 IS NOT NULL AND NEWROW.TEXT15 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT15 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT16 IS NOT NULL AND NEWROW.TEXT16 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT16 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT17 IS NOT NULL AND NEWROW.TEXT17 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT17 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT18 IS NOT NULL AND NEWROW.TEXT18 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT18 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT19 IS NOT NULL AND NEWROW.TEXT19 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT19 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF OLDROW.TEXT20 IS NOT NULL AND NEWROW.TEXT20 IS NULL THEN
  UPDATE DM_DEVICES
     SET TEXT20 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

--DICT--------------------------------------------------------------------------

IF (OLDROW.DICT_ID1 IS NOT NULL AND NEWROW.DICT_ID1 IS NULL) OR (OLDROW.DICT_ID1 != NEWROW.DICT_ID1) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID1 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID2 IS NOT NULL AND NEWROW.DICT_ID2 IS NULL) OR (OLDROW.DICT_ID2 != NEWROW.DICT_ID2) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID2 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID3 IS NOT NULL AND NEWROW.DICT_ID3 IS NULL) OR (OLDROW.DICT_ID3 != NEWROW.DICT_ID3) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID3 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID4 IS NOT NULL AND NEWROW.DICT_ID4 IS NULL) OR (OLDROW.DICT_ID4 != NEWROW.DICT_ID4) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID4 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID5 IS NOT NULL AND NEWROW.DICT_ID5 IS NULL) OR (OLDROW.DICT_ID5 != NEWROW.DICT_ID5) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID5 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID6 IS NOT NULL AND NEWROW.DICT_ID6 IS NULL) OR (OLDROW.DICT_ID6 != NEWROW.DICT_ID6) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID6 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID7 IS NOT NULL AND NEWROW.DICT_ID7 IS NULL) OR (OLDROW.DICT_ID7 != NEWROW.DICT_ID7) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID7 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID8 IS NOT NULL AND NEWROW.DICT_ID8 IS NULL) OR (OLDROW.DICT_ID8 != NEWROW.DICT_ID8) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID8 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID9 IS NOT NULL AND NEWROW.DICT_ID9 IS NULL) OR (OLDROW.DICT_ID9 != NEWROW.DICT_ID9) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID9 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID10 IS NOT NULL AND NEWROW.DICT_ID10 IS NULL) OR (OLDROW.DICT_ID10 != NEWROW.DICT_ID10) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID10 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID11 IS NOT NULL AND NEWROW.DICT_ID11 IS NULL) OR (OLDROW.DICT_ID11 != NEWROW.DICT_ID11) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID11 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID12 IS NOT NULL AND NEWROW.DICT_ID12 IS NULL) OR (OLDROW.DICT_ID12 != NEWROW.DICT_ID12) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID12 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID13 IS NOT NULL AND NEWROW.DICT_ID13 IS NULL) OR (OLDROW.DICT_ID13 != NEWROW.DICT_ID13) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID13 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID14 IS NOT NULL AND NEWROW.DICT_ID14 IS NULL) OR (OLDROW.DICT_ID14 != NEWROW.DICT_ID14) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID14 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID15 IS NOT NULL AND NEWROW.DICT_ID15 IS NULL) OR (OLDROW.DICT_ID15 != NEWROW.DICT_ID15) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID15 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID16 IS NOT NULL AND NEWROW.DICT_ID16 IS NULL) OR (OLDROW.DICT_ID16 != NEWROW.DICT_ID16) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID16 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID17 IS NOT NULL AND NEWROW.DICT_ID17 IS NULL) OR (OLDROW.DICT_ID17 != NEWROW.DICT_ID17) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID17 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID18 IS NOT NULL AND NEWROW.DICT_ID18 IS NULL) OR (OLDROW.DICT_ID18 != NEWROW.DICT_ID18) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID18 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID19 IS NOT NULL AND NEWROW.DICT_ID19 IS NULL) OR (OLDROW.DICT_ID19 != NEWROW.DICT_ID19) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID19 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

IF (OLDROW.DICT_ID20 IS NOT NULL AND NEWROW.DICT_ID20 IS NULL) OR (OLDROW.DICT_ID20 != NEWROW.DICT_ID20) THEN
  UPDATE DM_DEVICES
     SET DICT_VAL_ID20 = NULL
   WHERE OBJECT_ID = NEWROW.OBJECT_ID;
END IF;

END




--DROP TRIGGER TRG_DM_FIELDS_AFTER_UPDATE

