CREATE TRIGGER TRG_CC_DEVICES_AFTER_UPDATE AFTER UPDATE ON CC_DEVICES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
INSERT INTO H_CC_DEVICES(WHO_MODIFY, ACTION, ID, OLD_HOST, OLD_LOGIN, OLD_PWD, OLD_ENABLE_PWD, OLD_NAME, OLD_COMMENT, OLD_DEVICE_TYPE_NAME, 
                                                 OLD_CONNECT_TYPE, OLD_GET_CONFIG_INTERVAL, OLD_STORE_CONFIG_DAYS, OLD_CC_OBJECT_NAME,
                                                 NEW_HOST, NEW_LOGIN, NEW_PWD, NEW_ENABLE_PWD, NEW_NAME, NEW_COMMENT, NEW_DEVICE_TYPE_NAME, 
                                                 NEW_CONNECT_TYPE, NEW_GET_CONFIG_INTERVAL, NEW_STORE_CONFIG_DAYS, NEW_CC_OBJECT_NAME)
VALUES (USER_GET_AUTH(), 'U', NEW.ID, OLD.HOST, OLD.LOGIN, OLD.PWD, OLD.ENABLE_PWD, OLD.NAME, OLD.COMMENT, DEVICE_TYPE_GET_NAME(OLD.DEVICE_TYPE_ID), 
                                         OLD.CONNECT_TYPE, OLD.GET_CONFIG_INTERVAL, OLD.STORE_CONFIG_DAYS, CC_OBJECT_GET_NAME(OLD.CC_OBJECT_ID),
                                         NEW.HOST, NEW.LOGIN, NEW.PWD, NEW.ENABLE_PWD, NEW.NAME, NEW.COMMENT, DEVICE_TYPE_GET_NAME(NEW.DEVICE_TYPE_ID), 
                                         NEW.CONNECT_TYPE, NEW.GET_CONFIG_INTERVAL, NEW.STORE_CONFIG_DAYS, CC_OBJECT_GET_NAME(NEW.CC_OBJECT_ID))


DROP TRIGGER TRG_CC_DEVICES_AFTER_UPDATE



