CREATE TRIGGER TRG_DEVICES_BEFORE_INSERT BEFORE INSERT ON DEVICES
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN ATOMIC
  SET NEW.NAME = TRIM(NEW.NAME);
END

--DROP TRIGGER TRG_CC_DEVICES_AFTER_DELETE




