CREATE TRIGGER TRG_OBJECTS_AFTER_INSERT 
AFTER INSERT ON OBJECTS
REFERENCING NEW AS NEW
FOR EACH ROW
INSERT INTO H_OBJECTS(WHO_MODIFY, ACTION, ID, NEW_MAP_NAME, NEW_NAME, NEW_COMMENT)
VALUES (USER_ID(), 'I', NEW.ID, (SELECT NAME FROM MAPS WHERE ID = NEW.MAP_ID), NEW.NAME, NEW.COMMENT)


DROP TRIGGER TRG_OBJECTS_AFTER_INSERT 


