CREATE TRIGGER TRG_CC_DEVICES_AFTER_DELETE AFTER DELETE ON CC_DEVICES
REFERENCING OLD AS OLD
FOR EACH ROW
INSERT INTO H_CC_DEVICES(WHO_MODIFY, ACTION, ID, OLD_HOST, OLD_LOGIN, OLD_PWD, OLD_ENABLE_PWD, OLD_NAME, OLD_COMMENT, OLD_DEVICE_TYPE_NAME, 
                                                 OLD_CONNECT_TYPE, OLD_GET_CONFIG_INTERVAL, OLD_STORE_CONFIG_DAYS, OLD_CC_OBJECT_NAME)
VALUES (USER_GET_AUTH(), 'D', OLD.ID, OLD.HOST, OLD.LOGIN, OLD.PWD, OLD.ENABLE_PWD, OLD.NAME, OLD.COMMENT, DEVICE_TYPE_GET_NAME(OLD.DEVICE_TYPE_ID), 
                                         OLD.CONNECT_TYPE, OLD.GET_CONFIG_INTERVAL, OLD.STORE_CONFIG_DAYS, CC_OBJECT_GET_NAME(OLD.CC_OBJECT_ID))


DROP TRIGGER TRG_CC_DEVICES_AFTER_DELETE



