CREATE TRIGGER TRG_MAPS_AFTER_UPDATE AFTER UPDATE ON MAPS
REFERENCING NEW AS NEWROW OLD AS OLDROW
FOR EACH ROW
INSERT INTO H_MAPS(WHO_MODIFY, ACTION, ID, OLD_NAME, OLD_COMMENT, NEW_NAME, NEW_COMMENT)
VALUES (USER_ID(), 'U', NEWROW.ID, OLDROW.NAME, OLDROW.COMMENT, NEWROW.NAME, NEWROW.COMMENT)




DROP TRIGGER TRG_MAPS_AFTER_UPDATE

