CREATE TRIGGER TRG_MAPS_AFTER_DELETE AFTER DELETE ON MAPS
REFERENCING OLD AS OLDROW
FOR EACH ROW
INSERT INTO H_MAPS(WHO_MODIFY, ACTION, ID, OLD_NAME, OLD_COMMENT)
VALUES (USER_ID(), 'D', OLDROW.ID, OLDROW.NAME, OLDROW.COMMENT)




DROP TRIGGER TRG_MAPS_AFTER_DELETE

