CREATE TRIGGER TRG_PM_PORTS_AFTER_UPDATE 
AFTER UPDATE ON PM_PORTS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
INSERT INTO H_PM_PORTS(WHO_MODIFY, ACTION, ID, DEV_HOST, DEV_NAME, PORT, OLD_TELCO, OLD_PATCH, OLD_LOCATION, OLD_COMMENT, NEW_TELCO, NEW_PATCH, NEW_LOCATION, NEW_COMMENT)
SELECT USER_ID(), 'U', NEW.ID, D.HOST, D.NAME, NEW.PORT, OLD.TELCO, PO.PATCH, PO.LOCATION, OLD.COMMENT, NEW.TELCO, PN.PATCH, PN.LOCATION, NEW.COMMENT
FROM PM_DEVICES PD
JOIN DEVICES D ON D.ID = PD.DEVICE_ID
LEFT JOIN PM_PATCH PO ON PO.ID = OLD.PM_PATCH_ID
LEFT JOIN PM_PATCH PN ON PN.ID = NEW.PM_PATCH_ID
WHERE PD.ID = NEW.PM_DEVICE_ID
  AND USER_ID() IS NOT NULL
  AND (NVL(OLD.TELCO,'') != NVL(NEW.TELCO,'')
    OR NVL(PO.PATCH,'') != NVL(PN.PATCH,'')
    OR NVL(PO.LOCATION,'') != NVL(PN.LOCATION,'')
    OR NVL(OLD.COMMENT,'') != NVL(NEW.COMMENT,''))




DROP TRIGGER TRG_PM_PORTS_AFTER_UPDATE 

