CREATE TRIGGER TRG_CC_DEVICES_AFTER_INSERT AFTER INSERT ON CC_DEVICES
REFERENCING NEW AS NEW
FOR EACH ROW
INSERT INTO H_CC_DEVICES(WHO_MODIFY, ACTION, ID, NEW_HOST, NEW_LOGIN, NEW_PWD, NEW_ENABLE_PWD, NEW_NAME, NEW_COMMENT, NEW_DEVICE_TYPE_NAME, 
                                                 NEW_CONNECT_TYPE, NEW_GET_CONFIG_INTERVAL, NEW_STORE_CONFIG_DAYS, NEW_CC_OBJECT_NAME)
VALUES (USER_GET_AUTH(), 'I', NEW.ID, NEW.HOST, NEW.LOGIN, NEW.PWD, NEW.ENABLE_PWD, NEW.NAME, NEW.COMMENT, DEVICE_TYPE_GET_NAME(NEW.DEVICE_TYPE_ID), 
                                      NEW.CONNECT_TYPE, NEW.GET_CONFIG_INTERVAL, NEW.STORE_CONFIG_DAYS, CC_OBJECT_GET_NAME(NEW.CC_OBJECT_ID))
                                      


DROP TRIGGER TRG_CC_DEVICES_AFTER_INSERT                                      





