CREATE TRIGGER TRG_OBJECTS_AFTER_UPDATE 
AFTER UPDATE ON OBJECTS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
INSERT INTO H_OBJECTS(WHO_MODIFY, ACTION, ID, OLD_MAP_NAME, OLD_NAME, OLD_COMMENT, NEW_MAP_NAME, NEW_NAME, NEW_COMMENT)
VALUES (USER_ID(), 'U', NEW.ID, (SELECT NAME FROM MAPS WHERE ID = OLD.MAP_ID), OLD.NAME, OLD.COMMENT, (SELECT NAME FROM MAPS WHERE ID = NEW.MAP_ID), NEW.NAME, NEW.COMMENT)




DROP TRIGGER TRG_OBJECTS_AFTER_UPDATE 

