CREATE TRIGGER TRG_PM_PORTS_AFTER_INSERT 
AFTER INSERT ON PM_PORTS
REFERENCING NEW AS NEW
FOR EACH ROW
INSERT INTO H_PM_PORTS(WHO_MODIFY, ACTION, ID, DEV_HOST, DEV_NAME, PORT, NEW_TELCO, NEW_PATCH, NEW_LOCATION, NEW_COMMENT)
SELECT USER_ID(), 'I', NEW.ID, D.HOST, D.NAME, NEW.PORT, NEW.TELCO, P.PATCH, P.LOCATION, NEW.COMMENT
FROM PM_DEVICES PD
JOIN DEVICES D ON D.ID = PD.DEVICE_ID
LEFT JOIN PM_PATCH P ON P.ID = NEW.PM_PATCH_ID
WHERE PD.ID = NEW.PM_DEVICE_ID
  AND USER_ID() IS NOT NULL


DROP TRIGGER TRG_PM_PORTS_AFTER_INSERT 





