CREATE TABLE CONSOLE_LOG (
  DEVICE_HOST D_VC NOT NULL,
  DEVICE_NAME D_VC NOT NULL,  
  WHO_SENT INTEGER NOT NULL,
  WHEN_SENT TIMESTAMP NOT NULL,
  COMMAND D_VC_LONG NOT NULL,
  CONSTRAINT CONSOLE_LOG_REF_USERS FOREIGN KEY (WHO_SENT) REFERENCES USERS(ID)
)

DROP TABLE CONSOLE_LOG
