CREATE DOMAIN D_CONNECT_TYPE AS VARCHAR(10) CHECK (VALUE IN ('SSH','TELNET'));

CREATE DOMAIN D_SCRIPT_TYPE AS VARCHAR(30) CHECK (VALUE IN ('DOWNLOAD_CONFIGURATION','CONSOLE_AUTH','DEVICE_MANAGE','GET_ARP'));

CREATE DOMAIN D_OBJECT_TYPE AS VARCHAR(30) CHECK (VALUE IN ('CONFIG_CONTROL','PORT_MANAGE','DEVICE_MANAGE'));

CREATE DOMAIN D_GET_CONFIG_RESULT AS VARCHAR(10) CHECK (VALUE IN ('UNCHANGED','CHANGED','ERROR'));

CREATE DOMAIN D_RESULT AS VARCHAR(10) CHECK (VALUE IN ('OK','ERROR'));

CREATE DOMAIN D_TABLE_ACTION AS CHAR(1) CHECK (VALUE IN ('I','U','D'));

CREATE DOMAIN D_VC AS VARCHAR(100);

CREATE DOMAIN D_VC_LONG AS VARCHAR(1000);

CREATE DOMAIN D_VC_CLOB AS VARCHAR(16777216);

CREATE DOMAIN D_SCRIPT AS VARCHAR(10000);



