CREATE TABLE H_DEVICES (
  WHO_MODIFY INTEGER NOT NULL,
  WHEN_MODIFY TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,   
  ACTION D_TABLE_ACTION NOT NULL,
  
  ID INT, 
  MAP D_VC,
  
  OLD_NAME D_VC,
  OLD_LOCATION D_VC_LONG,
  OLD_COMMENT D_VC_LONG,
  OLD_DEVICE_TYPE D_VC,
  OLD_HOST D_VC,
  OLD_LOGIN D_VC ,
  OLD_PWD D_VC ,
  OLD_ENABLE_PWD D_VC ,
  OLD_CONNECT_TYPE D_VC,
  OLD_CONSOLE_PORT INTEGER ,  
  OLD_SNMP_VERSION INTEGER ,
  OLD_SNMP_PORT INTEGER ,
  OLD_READ_COMMUNITY D_VC ,
  OLD_WRITE_COMMUNITY D_VC ,

  NEW_NAME D_VC,
  NEW_LOCATION D_VC_LONG,
  NEW_COMMENT D_VC_LONG,
  NEW_DEVICE_TYPE D_VC,
  NEW_HOST D_VC,
  NEW_LOGIN D_VC ,
  NEW_PWD D_VC ,
  NEW_ENABLE_PWD D_VC ,
  NEW_CONNECT_TYPE D_VC,
  NEW_CONSOLE_PORT INTEGER ,  
  NEW_SNMP_VERSION INTEGER ,
  NEW_SNMP_PORT INTEGER ,
  NEW_READ_COMMUNITY D_VC ,
  NEW_WRITE_COMMUNITY D_VC ,  
   
  CONSTRAINT H_DEVICES_REF_USERS FOREIGN KEY (WHO_MODIFY) REFERENCES USERS(ID)
)



DROP TABLE H_DEVICES

