CREATE TABLE PM_ARP (
  OBJECT_ID INT NOT NULL,
  PM_DEVICE_ID INT NOT NULL,
  MAC D_VC NOT NULL,
  IP D_VC NOT NULL,
  DETECTED TIMESTAMP NOT NULL,
  
  CONSTRAINT PM_ARP_UNIQUE UNIQUE (OBJECT_ID,MAC,IP),
  CONSTRAINT PM_ARP_REF_OBJECTS FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS(ID) ON DELETE CASCADE,
  CONSTRAINT PM_ARP_REF_PM_DEVICES FOREIGN KEY (PM_DEVICE_ID) REFERENCES PM_DEVICES(ID) ON DELETE CASCADE
)


DROP TABLE PM_ARP
