CREATE TABLE ROLE_CONF_DEVICES (
  ROLE_ID INT NOT NULL,
  MAP_ID INT NOT NULL,
  CONSTRAINT ROLE_CONF_DEVICES_PK PRIMARY KEY (ROLE_ID, MAP_ID),
  CONSTRAINT ROLE_CONF_DEVICES_REF_MAPS FOREIGN KEY (MAP_ID) REFERENCES MAPS(ID) ON DELETE CASCADE,
  CONSTRAINT ROLE_CONF_DEVICES_REF_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
)
 
 
 DROP TABLE ROLE_CONF_DEVICES

