CREATE TABLE ROLE_NEW_CLIENT_NOTICE (
  ROLE_ID INT NOT NULL,
  OBJECT_ID INT NOT NULL,
  CONSTRAINT ROLE_NEW_CLIENT_NOTICE_PK PRIMARY KEY (ROLE_ID, OBJECT_ID),
  CONSTRAINT ROLE_NEW_CLIENT_NOTICE_REF_OBJECTS FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS(ID) ON DELETE CASCADE,
  CONSTRAINT ROLE_NEW_CLIENT_NOTICE_REF_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
)
 
 
 DROP TABLE ROLE_NEW_CLIENT_NOTICE


