CREATE VIEW V_ALL_MACS AS
SELECT DISTINCT D.OBJECT_ID, C.MAC
FROM PM_DEVICES D
JOIN PM_PORTS P ON P.PM_DEVICE_ID = D.ID
JOIN PM_PORT_CLIENTS C ON C.PM_PORT_ID = P.ID
WHERE C.MAC IS NOT NULL
UNION
SELECT DISTINCT A.OBJECT_ID, A.MAC 
FROM PM_CLIENTS_ARC A
WHERE A.MAC IS NOT NULL

