CREATE VIEW V_PM_PORT_CLIENTS AS
SELECT C.*, P.PM_DEVICE_ID, D.OBJECT_ID, P.PORT, P.TRUNK, P.TELCO, PA.PATCH, PA.LOCATION, DD.HOST, DD.NAME AS DEV_NAME, DD.LOCATION AS DEV_LOCATION, DD.COMMENT AS DEV_COMMENT
  FROM PM_PORT_CLIENTS C
  JOIN PM_PORTS P ON P.ID = C.PM_PORT_ID
  LEFT JOIN PM_PATCH PA ON PA.ID = P.PM_PATCH_ID
  JOIN PM_DEVICES D ON D.ID = P.PM_DEVICE_ID
  JOIN DEVICES DD ON DD.ID = D.DEVICE_ID



DROP VIEW V_PM_PORT_CLIENTS
